language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - android-22
    - add-on
    - extra
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  - chmod +x gradlew

script: ./gradlew clean build
#script: sh gradle/build.sh

notifications:
  email: false