language: android

android:
  components:
    - build-tools-30.0.3
    - android-30

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  - chmod +x gradlew

script: ./gradlew clean build
#script: sh gradle/build.sh

notifications:
  email: false