language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  - chmod +x gradlew

script: sh gradle/build.sh

notifications:
  email: false